### ISSUE TITLE
Lido2Mapsme+ beta publié

### ISSUE THREAD

**Issue by flyingeek** [flyingeek/editolido#1]
[à lire sur le Readme](https://github.com/flyingeek/editolido)

**Comment by flyingeek** [comment]
Pour les bugs report merci de m'envoyer si possible une copie des données en entrée qui par défaut sont dans Editorial/_lido2mapsme_/data/filename.txt

**Comment by flyingeek** [comment]
Release 1.0.1 dispo

Bien lire la rubrique Changements...

[Instructions](https://github.com/flyingeek/editolido)

**Comment by agaiddon** [comment]
![image](https://cloud.githubusercontent.com/assets/18113237/14074976/75386e46-f4d5-11e5-85ce-f49cddfe8ee2.png)

Bonjour après avoir pris les Workflows ici sur ce site, j'ai ce message dans la photo jointe.
Merci.
AG.

**Comment by niklas777** [comment]
Tu as suivi le procès du readme d'eric, la fin du reedme.

**Comment by flyingeek** [comment]
Il faut envoyer le PDF qui ne doit pas être reconnu.
Sinon Pb d'installation et suivre les consignes du readme (changements/utilisateurs beta).

**Comment by agaiddon** [comment]
Ok je vais voir ça dès que possible et je vous tiens au courant. 
Merci.

**Comment by agaiddon** [comment]
[BST_AF1753 _UKBB_LFPG_20160328_1215z.pdf](https://github.com/flyingeek/editolido/files/192548/BST_AF1753._UKBB_LFPG_20160328_1215z.pdf)
Bonsoir, 

Je pense avoir lu le readme comme il fallait.
Cet OFP fonctionne-t-il chez vous ?
AG.

**Comment by flyingeek** [comment]
Non, d'ailleurs la nouvelle version indique un pb dans les logs.... Je regarde

**Comment by flyingeek** [comment]
1.0.4 publiée (relancer avec mise à jour auto activée)
