### ISSUE TITLE
Plantage du Workflow gramet

### ISSUE THREAD

**Issue by agaiddon** [flyingeek/editolido#19]
Bonjour,
Malgré un redémarrage du pilotPad, rien n'y fait et le Workflow Lido2Gramet+ plante peu après get images from input. 
Ça ne me le fait que depuis hier et je n'ai fait aucune modif depuis. 
Ça vous le fait aussi ?
merci

**Comment by niklas777** [comment]
Ça me le fait sur le vol retour systématiquement

**Comment by flyingeek** [comment]
Il faut les pdf

**Comment by niklas777** [comment]
Le jour du vol à H-3, ça ne fonctionnait pas...

[20160601_0250z_AF349 _CYUL_LFPG.pdf](https://github.com/flyingeek/editolido/files/295391/20160601_0250z_AF349._CYUL_LFPG.pdf)

[20160523_0200z_AF275 _RJAA_LFPG.pdf](https://github.com/flyingeek/editolido/files/295392/20160523_0200z_AF275._RJAA_LFPG.pdf)

**Comment by flyingeek** [comment]
Il faut modifier dans l'app Workflow le workflow Lido2Gramet

Et modifier le filtre Filter Images Where:
remplacer Width is greater than 500
Par
Name begins with gramet

Workflow a résolu le bug du clipboard dans sa dernière mise à jour mais en a introduit un nouveau....

Lien à jour:

https://workflow.is/workflows/18b515bd2aea468884a66f9c75b14507

@niklas777 Merci de mettre ta doc à jour

**Comment by flyingeek** [comment]
Workflow à jour
