### ISSUE TITLE
Modification Format RLATSM

### ISSUE THREAD

**Issue by pgroell** [flyingeek/editolido#2]
Bonjour Eric,
Nous sommes maintenant autorisés à utiliser les tracks RLATSM. 
Le format a été modifié dans le TRACK MESSAGE, donc le décodage ne se fait plus dans le workflow.
Voir copie du TRACK MESSAGE attaché, (Track F)
![image](https://cloud.githubusercontent.com/assets/5833385/13852332/ff9fcdd2-ec37-11e5-8e9a-538b1450d739.png)

Sinon je n'ai pas encore eu le temps de tester correctement mais cela semble parfait.
Pascal

**Comment by flyingeek** [comment]
C'est corrigé, soit:

- Mettre à jour le workflow Editorial [Lido2Mapsme+](http://www.editorial-workflows.com/workflow/5800601703153664/o7BioyJJW8o#) (les personnalisations seront perdues)
- Modifier l'URL dans l'action Installation/Mise à jour et mettre 1.0.0.b5.zip au lieu de 1.0.0b4.zip

Sinon merci de m'envoyer une copie des données en entrée la prochaine fois (dans Editorial/_lido2mapsme_/data/)
