### ISSUE TITLE
Worflow ne fonctionne pas depuis un navigateur (Safari et Firefox testés).

### ISSUE THREAD

**Issue by pgroell** [flyingeek/editolido#20]
Tout est dans le titre, le Workflow fonctionne depuis un mail ou depuis une application PDF mais pas quand le PDF est affiché dans un navigateur (cas lorsqu'on passe par S4a). Je n'ai pas pu tester depuis PilotMission, pas de vol en ce moment.

EN PJ, copie ecran de Editorial, et PDF utilisé.

Pascal

![img_0585](https://cloud.githubusercontent.com/assets/5833385/22198721/0700ff18-e158-11e6-91c5-84e83216e247.PNG)
[https_%2Fs4a.airfrance.fr%2Fsuite%2Fbriefing%2Fview%2Fshowpdf.htm_flightId%09=11831.pdf](https://github.com/flyingeek/editolido/files/723165/https_.2Fs4a.airfrance.fr.2Fsuite.2Fbriefing.2Fview.2Fshowpdf.htm_flightId.09.11831.pdf)

**Comment by flyingeek** [comment]
De mon côté si tu ouvres le pdf dans GoodReader d'abord puis que tu envoies au workflow ça fonctionne, tu confirmes ?

**Comment by flyingeek** [comment]
J'ai teste avec l'archive que tu as mis sur github, s4a est vide pour moi.

**Comment by pgroell** [comment]
Je confirme que le PDF fonctionne dans un mail ou dans un lecteur de PDF permettant "Ouvrir dans".
En faisant un peu plus de recherches, ce qui pose problème est le navigateur et l'endroit depuis lequel tu lance le Workflow.
Sur Safari tu peux le lancer depuis le le lien "Options" en haut à gache et ça plante, si tu lances depuis le carré "Export" de la barre supérieure cela fonctionne.
Il se trouve que dans Firefox, le lien supérieur gauche n'existe pas et en haut à droite il y a un lien "Ouvrir" (qui remplace le lien "Ouvrir dans iBook" de Safari) et que le lancement du Workflow depuis ce lien plante le workflow, le lancement plante également avec le carré "Export" de la barre supérieure.
C'est naturellement fait avec le même OFP ouvert dans Safari puis dans Firefox.
Aucune idée de ce que cela donne dans PilotMission, pas de vols ne ce moment.

**Comment by flyingeek** [comment]
Pour moi le pb n'est pas lié aux workflows. Ça fonctionne sur le pdf, il faut donc trouver comment ton navigateur exporte un pdf. Sous safari iOS,  moi j'ai à droite ouvrir dans goodreader: nickel, à gauche Options... de là je peux aussi lancer les workflows sans pb contrairement à toi. L'icône export de safari (carré avec flèche) ne fonctionne pas par contre, je pense que c'est normal car Safari doit envoyer l'URL plutôt que le pdf.

**Comment by flyingeek** [comment]
La solution actuelle est de s'envoyer le pdf de s4a par mail.

**Comment by flyingeek** [comment]
Je viens de tester avec safari sur iPad, si je fais Options... Puis Run workflow puis Lido2Mapsme+ ça fonctionne parfaitement....
