### ISSUE TITLE
Chaînage des workflows

### ISSUE THREAD

**Issue by flyingeek** [flyingeek/editolido#24]
Plutôt que d'appeler chaque workflow depuis le pdf, j'ai finalement trouvé une méthode qui propose, à la fin du workflow, un menu pour en exécuter un autre.

Bonne idée ou trop compliqué ?

Workflows à tester:

[Lido2MapsMe+](https://workflow.is/workflows/6403d9869ffa43b68dd7746aa478e8dd)
[Lido2Gramet+](https://workflow.is/workflows/316b9cd9a23e4cdcb6107ab24a73ec4f)
[Lido2AvenzaMaps+](https://workflow.is/workflows/2fa164f2aa224fe3a1d7464445a17735)

Dans le principe il faut revenir à Workflow (en haut à gauche) après avoir importé le kml ou copié la route mPilot. Si on a choisi de visualiser le Gramet c'est après avoir touché "Done".

@pgroell
@niklas777

**Comment by flyingeek** [comment]
Nouvelle version avec commentaires

[Lido2MapsMe+](https://workflow.is/workflows/4dc301895df541659499734c8a023dce)
[Lido2Gramet+](https://workflow.is/workflows/fbe613e09d114f34a9489e16ea3c2985)
[Lido2AvenzaMaps+](https://workflow.is/workflows/c704966dbbc04b26a8d8781d54b7dbd6)

Comme on peut s'y perdre, le commentaire bien que discret permet de voir l'action utilisateur attendue.

![img_0252](https://cloud.githubusercontent.com/assets/68456/23120639/77c32cc4-f75d-11e6-9b59-72837d8221a9.PNG)

**Comment by pgroell** [comment]
Moi ça me va, il faut juster adapter le commentaire à tous les logiciels de cartographies. 
Un truc du style "Choisir l'application dans laquelle ouvrir la route" par exemple.
Pascal

**Comment by flyingeek** [comment]
![img_0255](https://cloud.githubusercontent.com/assets/68456/23177458/251c948c-f867-11e6-931d-4bdf021d8e77.PNG)

**Comment by flyingeek** [comment]
Ils sont publiés

**Comment by flyingeek** [comment]
Workflow 1.7.1 permet de lancer des sous workflows.

Du coup cela permet un workflow de ce type:

https://workflow.is/workflows/9930531fa5b4401a938ae51fafe482d3

(Pour que ça fonctionne bien il faut supprimer les menus créés dans les workflow précédents, soit le dernier bloc repeat et l'action Quicklook de Lido2Gramet)

C'est intéressant car on peut facilement crée son propre Workflow global et que ça limite le nombre d'action à choisir, par contre ça suppose que les utilisateurs programment ou adaptent ce workflow, on se retrouve pour les autres avec des workflows non chainables.

Votre avis ?

**Comment by pgroell** [comment]
Bonjour Eric,
moi j'aime bien, cela permet d'avoir un seul worflow qu'on peut adapter à son utilisation personelle.
Je trouve ça plus pertinent que le menu enfin de workflow.

**Comment by niklas777** [comment]
Après faut voir si pour l'utilisateur lambda ça ne sera pas trop
compliqué...
On ne pourra pas lancer mPilot comme c'est actuellement le cas ?

**Comment by pgroell** [comment]
En fait, mPilot se lance automatiquement à condition que tu aies modifié les workflow standards en supprimant le dernier Repeat (càd le menu) comme l'indique Eric.
Après quelques essais, je trouve ce workflow assez simple d'utilisation tout en gardant les workflows standards plus simples et indépendants.
Ce workflow est d'autre part assez simple et linéaire pour qu'il puisse être adapté aux besoins de chacun (Maps.me ou Avenza, Gramet ou pas, visualisation directe du Gramet ou pas).

**Comment by flyingeek** [comment]
On revient en fait à la situation d'il y a une semaine. Après la programmation Workflow est je pense à la hauteur d'un pilote surtout s'il a un exemple.

Envoyé de mon iPad

**Comment by niklas777** [comment]
je viens de mettre un nez dans le workflow My OFP workflow, c'est pas mal
du tout !! j'y ai même intégré mon workflow de sauvegarde automatique du
dossier pdf sur ma dropbox... je préfère avoir le gramet qui s'ouvre dans
le workflow gramet, donc j'ai viré le dernier appel au workflow revoir
gramet...
Je pense que pour simplifier les choses pour les pilotes, il faut mettre à
disposition un certains nombre de scénarii, il n'y a pas 50 use-cases... :

   1. Lido2Mapsme+ puis mPilot puis Lido2Gramet+ (cas où j'ai de l'internet)
   2. Lido2Mapsme+ puis mPilot (cas où je n'ai pas d'internet)
   3. Lido2Mapsme+ puis mPilot puis Lido2Gramet+ puis Lido2Avenza+ (cas où
   j'ai de l'internet)
   4. Lido2Mapsme+ puis mPilot puis Lido2Avenza+  (cas où je n'ai pas
   d'internet)

Je pense que si on donne ça en pâture aux pilotes ça leur permettra de ne
pas avoir à bidouiller outre mesure... faudrait pas les décourager...
Nico

PS important : dans la version 3 de pilotMission, l'export de l'OFP
n'existe plus... je féraille pour que ça revienne... pas gagné dans
l'optique d'une dématérialisation complète du dossier avec des morceaux de
différentes nature (pdf, xml, application tierce, etc). Néanmoins à noter
que l'export de la route vers mPilot est très bien fait, nos workflows ne
font pas mieux, le gramet perd de son intérêt avec eWAS et sa coupe
verticale, et Maps.me n'aura peut-être plus d'intérêt car eWAS a un module
airports avec présentation du sketches et des procédures disponibles qui
commence à être pas mal...

2017-03-03 12:08 GMT+01:00 flyingeek <notifications@github.com>:

> On revient en fait à la situation d'il y a une semaine. Après la
> programmation Workflow est je pense à la hauteur d'un pilote surtout s'il a
> un exemple.
>
> Envoyé de mon iPad
>

**Comment by flyingeek** [comment]
Sinon je propose un Workflow générique qui reprend en gros la version actuelle:

https://workflow.is/workflows/1ee33847096b485a9301680f45814a2a

**Comment by flyingeek** [comment]
C'est pour quand la v3 ?

**Comment by niklas777** [comment]
Instructeurs 7 mars, 100% mi-Avril

**Comment by niklas777** [comment]
je ne sais pas si je préfère celui-là...

**Comment by flyingeek** [comment]
Dans mon esprit My OFP Workflow doit être adapté par chaque utilisateur à son besoin, il s'agit juste d'un exemple, d'où le "My". Pour ceux qui ne le souhaitent pas on propose les workflows basiques et aussi ce workflow générique qui permet de chaîner les actions via un menu sans avoir à modifier quoi que ce soit.

Envoyé de mon iPad

**Comment by niklas777** [comment]
Ok !!

**Comment by flyingeek** [comment]
C'est publié
