### ISSUE TITLE
Affichage route Lido

### ISSUE THREAD

**Issue by niklas777** [flyingeek/editolido#25]
Salut,
actuellement, la route lido telle que créée par les workflows, présente seulement les points qui joignent les airways. Il se trouve que la future version de PilotMission fait différemment, elle présente tous les points de l'OFP ainsi que les airways entre eux. J'illustre la différence d'affichage avec les images jointes.
J'ai tendance à apprécier d'avoir tous les points affichés en permanence, qu'en pensez-vous ?
nicolas
![img_1192](https://cloud.githubusercontent.com/assets/17698636/23277450/292e8618-fa0e-11e6-8a63-dfa90b4fccd4.PNG)
![img_1194](https://cloud.githubusercontent.com/assets/17698636/23277451/29606246-fa0e-11e6-9ada-a28529c0a5ef.PNG)

**Comment by flyingeek** [comment]
Ce qui pourrait être sympa si c'est possible ce serait d'avoir juste les points des FIR.

**Comment by niklas777** [comment]
Oui, mais parfois il n'y a pas qu'un seul contrôle par FIR et il est donc
intéressant d'avoir les points intermédiaires...

**Comment by flyingeek** [comment]
Tu peux poster les 2 routes Lido pour voir ?

**Comment by niklas777** [comment]
J'ai mis des captures d'écran dans mon premier message

Le sam. 25 févr. 2017 à 03:40, flyingeek <notifications@github.com> a
écrit :

**Comment by flyingeek** [comment]
C’est le texte de la route qui m’intéresse

**Comment by niklas777** [comment]
J'ai pas... la route se load automatiquement... j'ai demandé la syntaxe
associée mais pas sur qu'ils me l'envoient...


Le sam. 25 févr. 2017 à 06:58, flyingeek <notifications@github.com> a
écrit :

> C’est le texte de la route qui m’intéresse
>

**Comment by flyingeek** [comment]
Comme on a le choix de L’import soit par le workflow, soit par Pilot Mission, je clôture.
