### ISSUE TITLE
Module editolido manquant

### ISSUE THREAD

**Issue by niklas777** [flyingeek/editolido#3]
Dans la console Pyhton j'obtiens le message "Module editolido manquant"...

**Comment by flyingeek** [comment]
Mauvaise URL ?

https://github.com/flyingeek/editolido/archive/1.0.0b5.zip

**Comment by flyingeek** [comment]
Sinon pour augmenter les logs, mettre temporairement log sur "Tout" toujours dans l'action "Installation"

**Comment by niklas777** [comment]
Je trouve où le log à envoyer ?

**Comment by flyingeek** [comment]
Il s'affiche dans la console

**Comment by niklas777** [comment]
excuse moi, je ne trouve pas ce que tu me dis...

**Comment by flyingeek** [comment]
On commence par lancer Editorial.

Si tu es dans la console, balayer avec un doigt de la gauche vers la droite

Maintenant tu es sur la vue normale d'Editorial, toucher en haut à droite l'icone en forme de clé, les workflows s'affichent.

Toucher le symbole i  à droite de Lido2Mapsme+, puis toucher Edit Workflow...

Toucher la première action (installation), elle se déplie, positionner Log à "Tout"

Ensuite lancer le Workflow en touchant l'icone Play (triangle) en haut à droite.

Si un dialogue s'affiche l'annuler, la console devrait être affichée, sinon balayer de la droite vers la gauche avec un doigt.

Tu peux éventuellement faire le menage dans la console en appuyant en haut à droite sur Clear, et recommencer la manip.

Ensuite copier coller de la console.

**Comment by flyingeek** [comment]
En plus du copier coller, une capture d'écran montrant l'action "Installation" dépliée peut être utile...

**Comment by niklas777** [comment]
​

**Comment by flyingeek** [comment]
Ton dernier commentaire est vide...

**Comment by niklas777** [comment]
![img_0866](https://cloud.githubusercontent.com/assets/17698636/13872150/741f29b8-ece8-11e5-91f7-d9e12949ebb8.PNG)
![img_0867](https://cloud.githubusercontent.com/assets/17698636/13872151/74245abe-ece8-11e5-939f-b147117edc7c.PNG)

**Comment by flyingeek** [comment]
Humm....
Tu es connecté comment a Internet ?

on va édité le script.

Sur l'action "Installation" il y a une icône en forme de triangle sur la droite.
Cliquer et choisir Edit script.

Ligne 51

r = requests.get(github_url, verify=True, stream=True, timeout=(3, 30))

Il faut augmenter les valeurs de timeout, remplacer le 3 par 4 ou 5 devrait suffire je pense.

**Comment by niklas777** [comment]
ça ne change rien... c'est pendant la phase d'installation que ça merde
j'ai l'impression

2016-03-18 10:48 GMT+01:00 flyingeek <notifications@github.com>:

**Comment by niklas777** [comment]
bon je crois que j'ai trouvé ce qui merdait : les données téléchargées (répertoire editolido) étaient placées dans un répertoire site-package. j'ai déplacé editolido dans le répertoire Documents, et là ça fonctionne

**Comment by flyingeek** [comment]
Non, site-packages est normal.
En plus je ne comprends pas le download fail tout en ayant téléchargé le module.

Merci d'effacer ton module editolido et de recommencer. J'ai mis le workflow Editorial à jour pour avoir le status code dans les logs.

**Comment by niklas777** [comment]
J'ai mis à jour le workflow editorial
Premier lancement avec un OFP :
![img_0868](https://cloud.githubusercontent.com/assets/17698636/13874912/f4619766-ecfa-11e5-8827-745570d53f97.PNG)

En faisant juste tourner le workflow éditorial :
![img_0869](https://cloud.githubusercontent.com/assets/17698636/13874913/f49137e6-ecfa-11e5-846f-122da063ece1.PNG)

**Comment by flyingeek** [comment]
Oui mais là tu as foutu le bordel en mettant editolido dans Documents.

Efface editolido, mets les logs sur "tout"

Quitte Editorial (double click sur le bouton home), glisser l'app Editorial vers le haut. Relancer Editorial. Ça va relancer python.

Dans la console (en bas), si ça merde toujours, tape

import sys; print sys.path
Ça permettra de voir si il y a un pb à ce niveau là

**Comment by niklas777** [comment]
Lancement, et erreur à nouveau editolido manquant :
![img_0870](https://cloud.githubusercontent.com/assets/17698636/13875176/a76bb85e-ecfc-11e5-8a85-ca4b4d7fec7e.PNG)

après avoir fait import sys; print sys.path :
![img_0871](https://cloud.githubusercontent.com/assets/17698636/13875178/a79e2438-ecfc-11e5-97c2-986c59b0860a.PNG)

**Comment by flyingeek** [comment]
Bon déjà on a plus le download fail... Je regarde.

**Comment by flyingeek** [comment]
Bon assure toi qu'editolido est bien present dans site-packages (il doit y avoir un paquet de fichier .py qu'Editorial ne permet pas d'afficher).
Redemarre Editorial et relance le workflow toujours depuis Editorial

**Comment by niklas777** [comment]
editolido est bien dans site-package
éditorial relancé
ça fonctionne...

**Comment by flyingeek** [comment]
Good!

**Comment by flyingeek** [comment]
En fait après l'installation initiale il faut redémarrer Editorial

**Comment by flyingeek** [comment]
1.0.1 publiée

Bien lire la rubrique Changements...

[Instructions](https://github.com/flyingeek/editolido)
