### ISSUE TITLE
pas de tracks affichés ?

### ISSUE THREAD

**Issue by niklas777** [flyingeek/editolido#5]
sur cet OFP, les tracks ne s'affichent pas... erreur de ma part ? j'ai bien activé l'affichage des tracks

[Briefing_Package_(OFP_no__12_0_1).pdf](https://github.com/flyingeek/editolido/files/179840/Briefing_Package_.OFP_no__12_0_1.pdf)

**Comment by flyingeek** [comment]
Celui la est embêtant le texte de la conversion du pdf (interne à workflow app) est mauvais.

**Comment by flyingeek** [comment]
Bon en fait c'est pas trop grave, c'est juste en désordre. Fix dans 24-48h

**Comment by flyingeek** [comment]
Fixé par 1.0.0b7 d1f898241e95fc9310afefb6a788d66b9244e79d
