### ISSUE TITLE
OFP versions différentes...?

### ISSUE THREAD

**Issue by niklas777** [flyingeek/editolido#6]
Salut Eric,
sur mon retour NY j'ai eu un OFP qui ne fonctionnait pas avec la dernière version (b7)
[20160322_0245z_AF011 _KJFK_LFPG.pdf](https://github.com/flyingeek/editolido/files/186682/20160322_0245z_AF011._KJFK_LFPG.pdf)
J'ai l'impression qu'il y a plusieurs versions d'OFP... à comparer à celle que j'avais jointe dans une issue précédente
Nicolas

**Comment by flyingeek** [comment]
Le fix est fait 737c545c6c9224ef2cf97526d03e1827c6b209e0 mais je n'ai pas encore fait de release, ça ne devrait pas tarder.

**Comment by flyingeek** [comment]
Release 1.0.1, il faut tout reinstaller dans l'ordre.

Bien lire la rubrique Changements...

[Instructions](https://github.com/flyingeek/editolido)
