### ISSUE TITLE
Compréhension Workflow gramet 

### ISSUE THREAD

**Issue by agaiddon** [flyingeek/editolido#7]
_On peut le faire en paramétrant dans Editorial Lido2Gramet+ ou Lido2Mapsme+, c'est une question de goût. En choisissant de le faire depuis Lido2Mapsme+, il n'est pas possible de masquer la route Ogimet dans Mapsme, si on le fait depuis Lido2Gramet+ il faut envoyer la route dans Mapsme et du coup il faut passer par l'app Photos ou le workflow Revoir Gramet pour l'afficher._

Bonjour Eric, je ne comprends pas bien l'utilisation de ce paragraphe.
Quand j'utilise le Workflows gramet, le résultat est une route approchée et le résultat de ce workflow est une image coupe du vol suivant une route approchée de celle de l'OFP. Cette route est "visualisable" dans Mapsme selon ce qui est écrit dans le readme mais je n'y parviens pas.
J'ai bien créé le dossier Gramet. L'image est bien à l'intérieur de ce dossier dans l'application Photos.
Et après ?

Je comprends aussi qu'avec ce Workflow gramet de route approchée il n'est plus nécessaire de donner des terrains intermédiaires pour avoir la route approchée (non orthodromique) et que c'est fait automatiquement. On perd un peu la main sur le choix des terrains que l'on pouvait souhaiter voir apparaître sur le Gramet mais tant pis.
Merci de ton aide.
![image](https://cloud.githubusercontent.com/assets/18113237/14100893/03f98e92-f591-11e5-962a-f58327604884.png)

**Comment by niklas777** [comment]
Effectivement, avoir des terrains était intéressant parce qu'ils
s'affichaient en dessous de la route, mais sur LC, on est souvent loin de
terrains (voire Gramet ne les connaît pas), donc on obtient avec la méthode
d'eric des gramets vachement plus précis !
Pour que la route soit visualisa le dans maps.me, il faut que tu l'aies
paramétré dans editorial

**Comment by pgroell** [comment]
En fait, tu as deux endroits qui permettent de choisir d'afficher la route OGIMET.
C'est dans les paramètres des workflow Editorial soit dans Lido2Gramet+ soit dans Lido2Mapsme+. 
Il faut déplier la ligne du workflow qui est en vers et passer le curser OGIMET sur ON.
Il y a de grandes chances que sur MC cela se superpose à la route OFP, car il y a beaucoup de stations météo disponibles.
Il ne s'agit que de l'affichage de la route OGIMET, rien de plus.
Tu peux faire l'essai suivant : passer dans Lido2Gramet+ le paramètre à OGIMET sur ON et n'utiliser que ce workflow sur un OFP, la route OGIMET peut être copiée dans Mapsme et la coupe est disponible dans l'album photo. (naturellement il ne faut afficher que le résultat de cette action, tu devrais avoir une route en bleu clair)
Je ne sais pas si c'est plus clair!!!!

**Comment by niklas777** [comment]
eric, pourra-t-on à terme avoir une fusion des 2 workflows "+" avec
paramétrage des actions désirées par popup (avec ou sans recherche de
gramet, etc) ?

2016-03-29 10:17 GMT+02:00 pgroell <notifications@github.com>:

**Comment by agaiddon** [comment]
Bonjour Pascal,

J'ai modifié dans les 2 éditorial mentionnés et ça marche. Cf screenshot.
Merci
AG.
![image](https://cloud.githubusercontent.com/assets/18113237/14102997/3283821a-f59e-11e5-9111-2a73d9d91db4.png)

**Comment by agaiddon** [comment]
Re,

Gramet ne semble pas parvenir à prendre les bons horaires même avec un temps de roulage forfaitaire.
Normal?
[BST_AF1889 _LROP_LFPG_20160329_1210z.pdf](https://github.com/flyingeek/editolido/files/193193/BST_AF1889._LROP_LFPG_20160329_1210z.pdf)
![image](https://cloud.githubusercontent.com/assets/18113237/14104038/4ab04d00-f5a3-11e5-8624-55f579926b1b.png)

**Comment by pgroell** [comment]
L'horaire surligné en jaune est toujours en heure ronde, c'est une limitation du système OGIMET (http://www.ogimet.com/gramet_aero.phtml.en   pour voir le masque utilisé).
Par contre le fait que cela commence à 1100Z pour un vol à 12h10 (plus roulage) est sans doute un bug.

**Comment by flyingeek** [comment]
Il faut changer les paramètres dans les workflow Editorial
"Afficher Ogimet" pour Lido2mapsme ou "Générer kml" pour Lido2Gramet+

Envoyé de mon iPad

**Comment by flyingeek** [comment]
J'envoie un timestamp utc à Ogimet, il faudrait l'envoyer en heure loc on dirait...

Envoyé de mon iPad

**Comment by flyingeek** [comment]
Editorial utilise l'unique clipboard pour transmettre l'URL Gramet et la route mPilot, d'où les 2 workflow. Après il est peut être possible de faire une bidouille.

Envoyé de mon iPad

**Comment by pgroell** [comment]
SI je fais un test en direct depuis la page GRAMET, le tref dans l'URL est bien une heure UTC.
Autre question, ne serait-il pas plus simple de récupérer l'heure de décollage dans l'OFP cela permettrait de supprimer le roulage dans le workflow Editorial.

**Comment by pgroell** [comment]
Je pense que le problème peut-être lié à l'utilisation de la fonction mktime(). Voir ici une explication assez complète (ce n'est pas parce qu'on considère qu'une heure quelconqu est en UTC que les fonctions python retournent des timestamp UTC).
http://stackoverflow.com/questions/15447632/python-convert-utc-time-tuple-to-utc-timestamp
C'est juste une idée.

**Comment by flyingeek** [comment]
Je ne l'ai pas, il faudrait que je modifie les workflows, et comme c'est arrondi à l'heure entière sur ogimet... Bref 10mn sur le MC 20 sur le LC on est pas loin du compte

Envoyé de mon iPad

**Comment by flyingeek** [comment]
Je vais regarder ça.

Sinon est ce que les albums photo des workflow étaient Gramet ou est ce qu'ils étaient vides à l'installation ?

Envoyé de mon iPad

**Comment by flyingeek** [comment]
@niklas si tu veux un popup, tu peux sur l'action à configurer toucher le triangle sur la droite (bien viser) et faire un "Pause before running" avec un "Show Parameters". C'est à un truc comme ça que tu pensais ?

**Comment by flyingeek** [comment]
@pgroell J'ai vu que tu avais cloné le repo, j'ai écris une bafouille: https://github.com/flyingeek/editolido/wiki/Développeurs

**Comment by pgroell** [comment]
Oui, j'ai cloné le repo pour voir comment cela fonctionnait. Je n'ai pas encore fais de test grandeur nature sur le sujet. Merci pour l'info sur le sujet, ça dégrossit.

**Comment by flyingeek** [comment]
1.0.5 corrige le timestamp merci @pgroell

**Comment by flyingeek** [comment]
@agaiddon pour le paramètre Ogimet, il est inutile de le faire dans les 2 workflows, ça ralenti. Mieux vaut choisir l'un ou l'autre. Et sur MC, perso je laisserai les 2 sur OFF.

**Comment by agaiddon** [comment]
Bonjour Eric,
J'avais fait la modif pour générer le kml dans les deux "éditorial" car je découvrais et c'était pour voir ce que cela faisait. Maintenant je ne l'ai activé que dans le gramet.

A l'usage  et constatant que les coupes MC seront très très proches de la route OFP je laisserais peut-être les 2 sur OFF comme tu le suggères.

Pour le timestamp TU, que doit-on retenir ? Je viens d'essayer sur 3 OFP de ma dernière rotation et les 3 horaires sont à 13H dans le titre jaune fluo de la coupe OGIMET.
Le timestamp n'est-il à jour que pour les OFP du jour et à venir ?

Merci.

**Comment by flyingeek** [comment]
@agaiddon oui c'est bien ça si antérieur à maintenant, c'est maintenant. On ne peut pas interroger ogimet sur le passé.

**Comment by agaiddon** [comment]
Ok, merci.
