### ISSUE TITLE
NOOA Sigmet dans Lido2Gramet votre avis ?

### ISSUE THREAD

**Issue by flyingeek** [flyingeek/editolido#8]
Lido2Gramet suppose d'etre connecté, et comme ça parle de Meteo, je pourrais proposer une option pour intégrer les sigmets dans le kml qu'il génère.

Est ce une bonne idée ? 
Utilisez vous l'option de tracé ogimet et si oui depuis lido2mapsme ou depuis lido2gramet ?

Perso j'utilise plutôt lido2gramet pour pouvoir choisir d'afficher ou pas depuis Mapsme.

**Comment by pgroell** [comment]
Bonjour Eric,

je pense que cela aurait du sens d'avoir un seul workflow météo qui nécessite d'être connecté. 
Les workflows "carto pure" peuvent être utilisés hors connexions.
Cela permettrait également de très facilement modifier les affichages dans Mapsme.
Dans cette optique le tracé Ogimet dans lido2gramet est suffisant, je ne vois pas d'utilité à le garder dans lido2mapsme.
My 0,02cts

Pascal

**Comment by niklas777** [comment]
Suis d'accord avec ça !

**Comment by agaiddon** [comment]
Idem 😉

**Comment by flyingeek** [comment]
Bon par contre il faudra mettre à jour les workflows Editorial manuellement parce que ça ajoute/retire des paramètres. D'autres idées de paramètres tant que j'y suis ?

**Comment by flyingeek** [comment]
Au niveau des valeurs par défaut, il vaut mieux:

- Afficher SIGMETS ce qui dans workflow se traduit par open in maps.me
- Afficher OGIMET ce qui dans workflow se traduit par open in maps.me
- Afficher SIGMET/OGIMET ce qui dans workflow se traduit par open in maps.me
- Ne rien afficher ce qui se traduit par l'affichage du Gramet directement

Votre avis ?

**Comment by niklas777** [comment]
Choix 3
Est-ce parametrable dans éditorial du coup ?

**Comment by agaiddon** [comment]
Bonjour Eric, oui le 3 me semble pas mal. 
Puis WF revoir gramet.

**Comment by flyingeek** [comment]
@niklas777 parametrable oui, 2 Switch.

**Comment by niklas777** [comment]
Go !!

**Comment by flyingeek** [comment]
v1.1.0

Mise à jour requise des workflows Lido2Mapsme+ pour Editorial et Lido2Gramet+ pour Editorial, pensez à noter vos paramétrages si besoin.

- Lido2Mapsme+ se recentre sur la cartograhie en mode déconnecté, donc plus de route Ogimet.
- Lido2Gramet+ nécessitant déjà d’être connecté pour récupérer le Gramet, il récupère aussi les NOOA SIGMETs (paramétrable).
- En sortie Lido2Gramet+ génère un KML, il est donc proposé par Workflow d’ouvrir ce dernier dans Mapsme, mais il est toujours possible de juste afficher l’image du Gramet en désactivant les SIGMETs et Ogimet.
- La consultation des KML sous Google Earth respecte les choix de couleurs et de PINs, l’épaisseur des lignes a été augmentée à (width=6).

Rq: Workflow a un bug lorsque le clipboard est vide et Lido2Gramet+ se bloque. En attendant la mise à jour de l’app Workflow, il est recommandé de lancer Lido2Mapsme+ en premier, vous aurez ainsi la route mPilot dans le clipboard.
