### ISSUE TITLE
Format des lignes tracées dans les KML

### ISSUE THREAD

**Issue by agaiddon** [flyingeek/editolido#9]
Bonjour,

Les kml générés sur le site http://www.notreavion.net/convert/form.html et ouverts dans Google earth sont très lisibles, ce qui n'est pas le cas des kml générés par les workflows.(On voit bien ces derniers dans Maps.me (bien que l'ortho puisse être moins visible) mais dans dans GE le trait est imperceptible.

J'ai réussi à changer la couleur mais pas l'épaisseur. (Ni l'opacité je crois).

Comment avoir un meilleur rendu dans GE si c'est possible ?
Merci.

**Comment by flyingeek** [comment]
C'est google earth desktop, web, ipad ? J'utilise pas alors il faut que je vois à quoi ça ressemble et je modifierai les styles, c'est vrai que j'ai beaucoup simplifié les styles...

**Comment by agaiddon** [comment]
La plupart du temps c'est plutôt sur IPad que je le visionne. Je n'ai pas
remarqué si c'est différent sur desktop.

**Comment by pgroell** [comment]
Comme MapsMe ne gère pas les épaisseur de ligne je pense qu'Eric a supprimé le paramètre <width>  dans la définition de la ligne alors qu'il est à 3 dans ma version.
Je dis je pense car je ne suis pas sûr dans quel fichier se fait le formatage (kml.py sans doute mais je sèche un peu).

**Comment by flyingeek** [comment]
@pgroell c'est dans les [kml templates](https://github.com/flyingeek/editolido/tree/master/editolido/data)

**Comment by flyingeek** [comment]
Bon j'ai eu du mal pour les icônes mais c'est fait...ça respecte les couleurs choisies dans Google Earth :-)

43405a6ef7b09094bd86bbc119f372a39875f1f7

**Comment by agaiddon** [comment]
Merci Eric
Tu peux pousser à width 6 iso 3 pour essai dans GE ou ça mettrait le bazard dans M.m ?
AG

**Comment by flyingeek** [comment]
Ok je ferai ça

**Comment by agaiddon** [comment]
👏👍
